Get median
JadenBalogh/capstone-htb-git-demo pull request #2
Opened 2020-09-19 06:30 UTC by a1v1n1

Added unit tests

2020-09-20 05:42 UTC, JadenBalogh requested changes
Some formatting changes required. See comments.

2020-09-20 05:42 UTC, JadenBalogh commented on Main.java
>  			int mid = (int)(arr.length/2);
These still need a formatting pass to conform with our standards - you can use Alt+Shift+F in VS Code or follow the format of the existing methods to do this.

2020-09-20 06:00 UTC, JadenBalogh approved these changes
Looks good!

2020-09-22 17:54 UTC, merged

2020-09-22 17:55 UTC, Jaredhw commented
Approved - Merging into Master